name: Main Job Alert Bot

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # allows manual run

permissions:
  contents: write        # Required for pushing changes

jobs:
  run-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/speedyapply/JobSpy.git requests beautifulsoup4

      - name: Run test_job_alert.py
        env:
          SLACK_TEST: ${{ secrets.SLACK_TEST }}
        run: python test_job_alert.py
